AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    access-keys-rotation

    Sample SAM Template for access-keys-rotation

Resources:
    Queues:
        Type: AWS::Serverless::Application
        Properties:
            Location: src/queues/template.yaml

    DynamoDB:
        Type: AWS::Serverless::Application
        Properties:
            Location: src/db/template.yaml

    Alarms:
        Type: AWS::Serverless::Application
        Properties:
            Location: src/alarms/template.yaml
            Parameters:
                UserAccessKeyLookupDLQName: !GetAtt Queues.Outputs.UserAccessKeyLookupDLQName
                CreateUserAccessKeyDLQName: !GetAtt Queues.Outputs.CreateUserAccessKeyDLQName
                DLQAlarmBreachTopic: !GetAtt Queues.Outputs.DLQAlarmBreachTopic
                StoreSecretsDLQName: !GetAtt Queues.Outputs.StoreSecretsQueueDLQName
                DeleteOldAccessKeyDLQName: !GetAtt Queues.Outputs.DeleteOldAccessKeyQueueDLQName
                SendEmailDLQName: !GetAtt Queues.Outputs.SendEmailDLQName

    Functions:
        Type: AWS::Serverless::Application
        Properties:
            Location: src/functions/template.yaml
            Parameters:
                UserAccessKeyLookupQueueArn: !GetAtt Queues.Outputs.UserAccessKeyLookupQueueArn
                CreateUserAccessKeyQueueArn: !GetAtt Queues.Outputs.CreateUserAccessKeyQueueArn
                StoreSecretsQueueArn: !GetAtt Queues.Outputs.StoreSecretsQueueArn
                DynamoDBUserTableNameArn: !GetAtt DynamoDB.Outputs.DynamoDBUserTableNameArn
                SendEmailQueueArn: !GetAtt Queues.Outputs.SendEmailQueueArn
                UpdatedAccessKeyAndStoredSecretSNSTopic: !GetAtt Queues.Outputs.UpdatedAccessKeyAndStoredSecretSNSTopic
                DeleteOldAccessKeyQueueArn: !GetAtt Queues.Outputs.DeleteOldAccessKeyQueueArn
