AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  access-keys-rotation

  Sample SAM Template for access-keys-rotation

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  UserAccessKeyLookup:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: user-access-key-lookup/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: IAMListUsersPolicy
              Effect: Allow
              Action:
                - iam:ListUsers
              Resource: !Sub "arn:aws:iam::${AWS::AccountId}:user/*"
      Events:
        CloudWatchEvent:
          Type: Schedule # More info about Schedule Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
          Properties:
            Schedule: rate(1 day)
            Name: start-access-keys-check
            Description: Trigger a lambda function every 24 hours to check if access keys need to be rotated
            Enabled: True
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
  CheckAccessKeyAgeOfUserQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CheckAccessKeyAgeOfUserQueue
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "CheckAccessKeyAgeOfUserDLQ"
            - "Arn"
        maxReceiveCount: 5
  CheckAccessKeyAgeOfUserDLQ:
    Type: AWS::SQS::Queue

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UserAccessKeyLookupFunction:
    Description: "UserAccessKeyLookup Lambda Function ARN"
    Value: !GetAtt UserAccessKeyLookup.Arn
  UserAccessKeyLookupFunctionIamRole:
    Description: "Implicit IAM Role created for UserAccessKeyLookup function"
    Value: !GetAtt UserAccessKeyLookup.Arn
  CheckAccessKeyAgeOfUserQueueURL:
    Description: "The queue which UserAccessKeyLookup will send to"
    Value:
      Ref: "CheckAccessKeyAgeOfUserQueue"
